CREATE TABLE T_ACCOUNT_TYPE (
ID INTEGER IDENTITY PRIMARY KEY,
AccountType VARCHAR(15) NOT NULL);

CREATE TABLE T_ACCOUNTS (
ID INTEGER IDENTITY PRIMARY KEY,
AccountNumber INTEGER NOT NULL,
AccountName VARCHAR(80) NOT NULL,
AccountTypeId INTEGER NOT NULL,
AccountBalance DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
Currency VARCHAR(3) NOT NULL,
UNIQUE(AccountNumber),
FOREIGN KEY (AccountTypeId) references T_ACCOUNT_TYPE(ID));

CREATE TABLE T_TRANSACTION (
ID INTEGER IDENTITY PRIMARY KEY,
AccountId INTEGER NOT NULL,
TransactionDate DATE NOT NULL,
TransactionAmount DECIMAL(10,2) NOT NULL,
TransactionType VARCHAR(10) NOT NULL,
Currency VARCHAR(3) NOT NULL,
Comments VARCHAR(1000),
FOREIGN KEY (AccountId) references T_ACCOUNTS(ID));

